---
# tasks file for ansible-role-isakmpd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Enable ipsec
  service:
    name: ipsec
    enabled: true
  when: "{{ ansible_os_family == 'OpenBSD' }}"

- name: Create a directory for anchor flagments
  file:
    path: "{{ isakmpd_conf_dir }}"
    state: directory

- name: Create pf anchor file
  template:
    src: pf.conf.anchor.j2
    dest: "{{ isakmpd_conf_dir }}/ipsec_anchor.pf"
    mode: 0600
    validate: "pfctl -n -f %s -a ipsec"
  notify: Reload pf anchor

- name: Create ipsec.conf
  template:
    src: ipsec.conf.j2
    dest: "{{ isakmpd_conf }}"
    mode: 0600
    validate: "ipsecctl -n -f %s"
  notify:
    - Restart isakmpd

- name: Start isakmpd
  service:
    name: "{{ isakmpd_service }}"
    enabled: true
    state: started
    arguments: "{{ isakmpd_flags }}"
  notify:
    - Reload ipsec.conf
