---
# tasks file for ansible-role-isakmpd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create ipsec.conf
  template:
    src: ipsec.conf.j2
    dest: "{{ isakmpd_conf }}"
    mode: 0600
  notify: Restart isakmpd

- name: Start isakmpd
  service:
    name: "{{ isakmpd_service }}"
    enabled: true
    state: started
    arguments: "{{ isakmpd_flags }}"
