---

- name: Restart isakmpd
  service:
    name: "{{ isakmpd_service }}"
    state: restarted
  notify: Reload ipsec.conf

- name: Reload ipsec.conf
  command: "ipsecctl -f {{ isakmpd_conf }}"

- name: Reload pf anchor
  command: "pfctl -f {{ isakmpd_conf_dir }}/ipsec_anchor.pf  -a ipsec_anchor"
